### ISSUE TITLE
Runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by acsfer** [storj/gateway#19]
From `syslog`:
```
2020-08-27T00:58:37.296+0200#011INFO#011http: panic serving 10.1.0.2:63618: runtime error: invalid memory address or nil pointer dereference
goroutine 1347533 [running]:
net/http.(*conn).serve.func1(0xc0012b3e00)
#011/usr/local/go/src/net/http/server.go:1767 +0x139
panic(0x1b39d40, 0x30bae10)
#011/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/minio/minio/cmd.criticalErrorHandler.ServeHTTP.func1(0xc0004cb600, 0x22177a0, 0xc000728fc0)
#011/go/pkg/mod/github.com/minio/minio@v0.0.0-20200713165107-e7d7d5232c60/cmd/generic-handlers.go:757 +0x1a2
panic(0x1b39d40, 0x30bae10)
#011/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/spacemonkeygo/monkit/v3.newSpan.func1(0xc002a572d0)
#011/go/pkg/mod/github.com/spacemonkeygo/monkit/v3@v3.0.7-0.20200515175308-072401d8c752/ctx.go:147 +0x3a8
panic(0x1b39d40, 0x30bae10)
#011/usr/local/go/src/runtime/panic.go:679 +0x1b2
storj.io/gateway/miniogw.minioObjectInfo(0xc000cd2548, 0x11, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
#011/go/src/storj.io/storj/miniogw/gateway.go:741 +0x5c
storj.io/gateway/miniogw.(*gatewayLayer).DeleteObject(0xc00072d320, 0x2224ba0, 0xc0001adb30, 0xc000cd2548, 0x11, 0xc0006c70e0, 0xa, 0x0, 0x0, 0x0, ...)
#011/go/src/storj.io/storj/miniogw/gateway.go:109 +0x428
storj.io/gateway/miniogw.(*layerLogging).DeleteObject(0xc00072d340, 0x2224ba0, 0xc0001adb30, 0xc000cd2548, 0x11, 0xc0006c70e0, 0xa, 0x0, 0x0, 0x0, ...)
#011/go/src/storj.io/storj/miniogw/logging.go:131 +0xe8
github.com/minio/minio/cmd.newServerCacheObjects.func3(0x2224ba0, 0xc0001adb30, 0xc000cd2548, 0x11, 0xc0006c70e0, 0xa, 0x0, 0x0, 0x0, 0x0, ...)
#011/go/pkg/mod/github.com/minio/minio@v0.0.0-20200713165107-e7d7d5232c60/cmd/disk-cache.go:675 +0xe7
github.com/minio/minio/cmd.(*cacheObjects).DeleteObject(0xc0004c5c00, 0x2224ba0, 0xc0001adb30, 0xc000cd2548, 0x11, 0xc0006c70e0, 0xa, 0x0, 0x0, 0x0, ...)
#011/go/pkg/mod/github.com/minio/minio@v0.0.0-20200713165107-e7d7d5232c60/cmd/disk-cache.go:124 +0xe0
github.com/minio/minio/cmd.deleteObject(0x2224ba0, 0xc0001adb30, 0x226da80, 0xc00072d380, 0x223f4e0, 0xc0004c5c00, 0xc000cd2548, 0x11, 0xc0006c70e0, 0xa, ...)
#011/go/pkg/mod/github.com/minio/minio@v0.0.0-20200713165107-e7d7d5232c60/cmd/object-handlers-common.go:304 +0x172
github.com/minio/minio/cmd.objectAPIHandlers.DeleteObjectHandler(0x1ebe750, 0x1ebe740, 0xc000642350, 0xc000642360, 0x2211c20, 0xc000c46000, 0xc0004cb800)
#011/go/pkg/mod/github.com/minio/minio@v0.0.0-20200713165107-e7d7d5232c60/cmd/object-handlers.go:2659 +0x565
net/http.HandlerFunc.ServeHTTP(...)
#011/usr/local/go/src/net/http/server.go:2007
github.com/minio/minio/cmd.httpTraceAll.func1(0x2211c20, 0xc000c46000, 0xc0004cb800)
#011/go/pkg/mod/github.com/minio/minio@v0.0.0-20200713165107-e7d7d5232c60/cmd/handler-utils.go:342 +0x148
net/http.HandlerFunc.ServeHTTP(...)
#011/usr/local/go/src/net/http/server.go:2007
github.com/minio/minio/cmd.collectAPIStats.func1(0x2211c20, 0xc0008a4aa0, 0xc0004cb800)
#011/go/pkg/mod/github.com/minio/minio@v0.0.0-20200713165107-e7d7d5232c60/cmd/handler-utils.go:369 +0x111
net/http.HandlerFunc.ServeHTTP(...)
#011/usr/local/go/src/net/http/server.go:2007
github.com/minio/minio/cmd.maxClients.func1(0x2211c20, 0xc0008a4aa0, 0xc0004cb800)
#011/go/pkg/mod/github.com/minio/minio@v0.0.0-20200713165107-e7d7d5232c60/cmd/handler-api.go:89 +0x3b0
net/http.HandlerFunc.ServeHTTP(0xc0005c2e40, 0x2211c20, 0xc0008a4aa0, 0xc0004cb800)
#011/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/minio/minio/cmd.customHeaderHandler.ServeHTTP(0x21eb380, 0xc0005c2e40, 0x2211be0, 0xc0009d6520, 0xc0004cb800)
#011/go/pkg/mod/github.com/minio/minio@v0.0.0-20200713165107-e7d7d5232c60/cmd/generic-handlers.go:727 +0x162
github.com/minio/minio/cmd.securityHeaderHandler.ServeHTTP(0x21ea0c0, 0xc002a57060, 0x2211be0, 0xc0009d6520, 0xc0004cb800)
#011/go/pkg/mod/github.com/minio/minio@v0.0.0-20200713165107-e7d7d5232c60/cmd/generic-handlers.go:742 +0x1d6
github.com/minio/minio/cmd.bucketForwardingHandler.ServeHTTP(0xc0001ad590, 0x21ea220, 0xc002a57070, 0x2211be0, 0xc0009d6520, 0xc0004cb800)
#011/go/pkg/mod/github.com/minio/minio@v0.0.0-20200713165107-e7d7d5232c60/cmd/generic-handlers.go:600 +0xcc
github.com/minio/minio/cmd.requestValidityHandler.ServeHTTP(0x21ea020, 0xc0009d64c0, 0x2211be0, 0xc0009d6520, 0xc0004cb800)
#011/go/pkg/mod/github.com/minio/minio@v0.0.0-20200713165107-e7d7d5232c60/cmd/generic-handlers.go:584 +0x421
github.com/minio/minio/cmd.httpStatsHandler.ServeHTTP(0x21ea1c0, 0xc002a57090, 0x22177a0, 0xc000728fc0, 0xc0004cb800)
#011/go/pkg/mod/github.com/minio/minio@v0.0.0-20200713165107-e7d7d5232c60/cmd/generic-handlers.go:512 +0xe4
github.com/minio/minio/cmd.requestSizeLimitHandler.ServeHTTP(0x21ea0e0, 0xc002a570a0, 0x50004000000, 0x22177a0, 0xc000728fc0, 0xc0004cb800)
#011/go/pkg/mod/github.com/minio/minio@v0.0.0-20200713165107-e7d7d5232c60/cmd/generic-handlers.go:67 +0xcf
github.com/minio/minio/cmd.requestHeaderSizeLimitHandler.ServeHTTP(0x21ea1a0, 0xc0009d64e0, 0x22177a0, 0xc000728fc0, 0xc0004cb800)
#011/go/pkg/mod/github.com/minio/minio@v0.0.0-20200713165107-e7d7d5232c60/cmd/generic-handlers.go:92 +0x1b3
github.com/minio/minio/cmd.crossDomainPolicy.ServeHTTP(0x21ea180, 0xc002a570b0, 0x22177a0, 0xc000728fc0, 0xc0004cb800)
#011/go/pkg/mod/github.com/minio/minio@v0.0.0-20200713165107-e7d7d5232c60/cmd/crossdomain-xml-handler.go:51 +0x81
github.com/minio/minio/cmd.redirectHandler.ServeHTTP(0x21ea0a0, 0xc002a570c0, 0x22177a0, 0xc000728fc0, 0xc0004cb800)
#011/go/pkg/mod/github.com/minio/minio@v0.0.0-20200713165107-e7d7d5232c60/cmd/generic-handlers.go:250 +0x68
github.com/minio/minio/cmd.minioReservedBucketHandler.ServeHTTP(0x21ea160, 0xc002a570d0, 0x22177a0, 0xc000728fc0, 0xc0004cb800)
#011/go/pkg/mod/github.com/minio/minio@v0.0.0-20200713165107-e7d7d5232c60/cmd/generic-handlers.go:318 +0xac
github.com/minio/minio/cmd.cacheControlHandler.ServeHTTP(0x21ea120, 0xc002a570e0, 0x22177a0, 0xc000728fc0, 0xc0004cb800)
#011/go/pkg/mod/github.com/minio/minio@v0.0.0-20200713165107-e7d7d5232c60/cmd/generic-handlers.go:277 +0x1c2
github.com/minio/minio/cmd.timeValidityHandler.ServeHTTP(0x21ea040, 0xc002a570f0, 0x22177a0, 0xc000728fc0, 0xc0004cb800)
#011/go/pkg/mod/github.com/minio/minio@v0.0.0-20200713165107-e7d7d5232c60/cmd/generic-handlers.go:388 +0x3b5
github.com/minio/minio/cmd.resourceHandler.ServeHTTP(0x21ea260, 0xc002a57100, 0x22177a0, 0xc000728fc0, 0xc0004cb800)
#011/go/pkg/mod/github.com/minio/minio@v0.0.0-20200713165107-e7d7d5232c60/cmd/generic-handlers.go:492 +0xa5
github.com/minio/minio/cmd.authHandler.ServeHTTP(0x21ea200, 0xc002a57110, 0x22177a0, 0xc000728fc0, 0xc0004cb800)
#011/go/pkg/mod/github.com/minio/minio@v0.0.0-20200713165107-e7d7d5232c60/cmd/auth-handler.go:462 +0x2e1
github.com/minio/minio/cmd.sseTLSHandler.ServeHTTP(0x21ea000, 0xc002a57120, 0x22177a0, 0xc000728fc0, 0xc0004cb800)
#011/go/pkg/mod/github.com/minio/minio@v0.0.0-20200713165107-e7d7d5232c60/cmd/generic-handlers.go:778 +0x2a3
github.com/minio/minio/cmd.reservedMetadataHandler.ServeHTTP(0x21ea240, 0xc002a57130, 0x22177a0, 0xc000728fc0, 0xc0004cb800)
#011/go/pkg/mod/github.com/minio/minio@v0.0.0-20200713165107-e7d7d5232c60/cmd/generic-handlers.go:138 +0x1b3
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0001c40c0, 0x22177a0, 0xc000728fc0, 0xc0004cb600)
#011/go/pkg/mod/github.com/gorilla/mux@v1.7.5-0.20200711200521-98cb6bf42e08/mux.go:210 +0xe2
github.com/rs/cors.(*Cors).Handler.func1(0x22177a0, 0xc000728fc0, 0xc0004cb600)
#011/go/pkg/mod/github.com/rs/cors@v1.7.0/cors.go:219 +0x1b8
net/http.HandlerFunc.ServeHTTP(0xc000695c60, 0x22177a0, 0xc000728fc0, 0xc0004cb600)
#011/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/minio/minio/cmd.criticalErrorHandler.ServeHTTP(0x21eb380, 0xc000695c60, 0x22177a0, 0xc000728fc0, 0xc0004cb600)
#011/go/pkg/mod/github.com/minio/minio@v0.0.0-20200713165107-e7d7d5232c60/cmd/generic-handlers.go:760 +0xac
github.com/minio/minio/cmd/http.(*Server).Start.func1(0x22177a0, 0xc000728fc0, 0xc0004cb600)
#011/go/pkg/mod/github.com/minio/minio@v0.0.0-20200713165107-e7d7d5232c60/cmd/http/server.go:98 +0x2ab
net/http.HandlerFunc.ServeHTTP(0xc0006bc060, 0x22177a0, 0xc000728fc0, 0xc0004cb600)
#011/usr/local/go/src/net/http/server.go:2007 +0x44
net/http.serverHandler.ServeHTTP(0xc0008a1c20, 0x22177a0, 0xc000728fc0, 0xc0004cb600)
#011/usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc0012b3e00, 0x2224ae0, 0xc000cc4cc0)
#011/usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
#011/usr/local/go/src/net/http/server.go:2928 +0x384
```
As my previous issue https://github.com/storj/gateway/issues/18 this also causes 100% CPU until service restart.

**Comment by ifraixedes** [comment]
@acsfer thanks for reporting.

A few weeks ago, we spotted `invalid memory address or nil pointer dereference` using the gateway with some applications. We have tracked the problem in our internal issue tracker.

I would like to ask you if you could confirm that you have seen this error using the same application than the ones commented in #18 which are `Nextcloud v19.0.1` and `mc` (MinIO), because that we'll help us to identify the problem when we start to work on it.

Many thanks for your collaboration.

**Comment by acsfer** [comment]
Yes, we only use the Gateway for that environment.
Note we are using minio cache too:

```
[Unit]
Description=Storj Gateway service
After=syslog.target network.target
Wants=network-online.target

[Service]
User=storj
Group=storj
ExecStart=/usr/local/bin/gateway run --config-dir=/etc/storj/gateway
Restart=always
RestartSec=5s
Type=simple
NotifyAccess=main
AmbientCapabilities=CAP_NET_BIND_SERVICE
NoNewPrivileges=yes
LimitMEMLOCK=infinity
LimitNOFILE=65535

StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=storj-gateway
Nice=10

Environment=MINIO_CACHE=on
Environment=MINIO_CACHE_DRIVES=/mnt/cache/storj
Environment=MINIO_CACHE_EXPIRY=3650
Environment=MINIO_CACHE_QUOTA=90
Environment=MINIO_CACHE_WATERMARK_LOW=80
Environment=MINIO_CACHE_WATERMARK_HIGH=95
Environment=MINIO_CACHE_AFTER=1

[Install]
WantedBy=multi-user.target
```

**Comment by acsfer** [comment]
With Nextcloud, problem can be triggered each time you run:

`sudo -u www-data php occ trashbin:clean --all-users`

**Comment by VinozzZ** [comment]
Hey there, thank you for providing the log information. Do you mind to share what version of gateway are you running?

**Comment by acsfer** [comment]
@VinozzZ 

```
gateway version
Release build
Version: v1.1.6
Build timestamp: 11 Aug 20 10:36 CEST
Git commit: 4016671861a49f330a736f1740a65c7c9d253852
```

**Comment by VinozzZ** [comment]
Thank you for the quick response. I was able to reproduce it with v1.1.6. Our team has merged the fix into master but hasn't made a release since then. I will work on a new release and after that, this issue should be solved with the new release.

**Comment by VinozzZ** [comment]
Hi @acsfer , we just released a new version of gateway with the fix. Let us know if you are still experiencing issues. Thanks again for reporting the problem

**Comment by acsfer** [comment]
Hi @VinozzZ indeed it seems fixed.

As least command `sudo -u www-data php occ trashbin:clean --all-users` doesn't not produce errors anymore and files are correctly deleted. I'll close for now. Thanks 👍
